# Generated by Django 5.1.2 on 2024-10-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_alter_bankdetail_mobile_registerform'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_acc', models.IntegerField(max_length=10)),
                ('current_acc', models.IntegerField(max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registerform',
            name='account_type',
            field=models.ManyToManyField(to='Homepage.account'),
        ),
    ]
